### ISSUE TITLE
regarding project repository

### ISSUE THREAD

**Issue by Dhruva410** [kwwongao/Ustar#1]
Hello,

In this code there is no app folder ..then how to work in android studio?
if you have proper code or example of augment reality core indoor navigation then please share with me as soon as possible because i didn't get any proper solution of that.

Thanking You

**Comment by sohailg** [comment]
Made in Unity

**Comment by albertwong25** [comment]
> Hello,
> 
> In this code there is no app folder ..then how to work in android studio?
> if you have proper code or example of augment reality core indoor navigation then please share with me as soon as possible because i didn't get any proper solution of that.
> 
> Thanking You

**Comment by albertwong25** [comment]
> Hello,
> 
> In this code there is no app folder ..then how to work in android studio?
> if you have proper code or example of augment reality core indoor navigation then please share with me as soon as possible because i didn't get any proper solution of that.
> 
> Thanking You

The project is built by Eclipse, which is not in gradle structure.
